### ISSUE TITLE
Using DefaultStorageProvider with PersistentDataPath gives an error 

### ISSUE THREAD

**Issue by Chiel75** [segmentio/Analytics-CSharp#86] opened 2024-02-06 08:09 UTC
Error in the public class FileEventStream

In the Analytics.CSharp version 2.3.2 source code:

In the eventoutputstream, line 204 
                _fs = _file.Open(FileMode.Append);
should be
                _fs = _file.Open(FileMode.Append, FileAccess.Write);

As FileMode.Append will throw an error withot the FileAcces.Write. Please see the intellisense:
![image](https://github.com/segmentio/Analytics-CSharp/assets/133342620/4e32b78a-fdf0-43b1-ae9f-38540686148f)

**Comment by wenxi-zeng** [comment] 2024-02-06 16:21
hi @Chiel75 thanks for reporting this. can you confirm what platform you're seeing this issue please? is it Unity?

**Comment by wenxi-zeng** [comment] 2024-02-07 16:58
@Chiel75 we cannot reproduce the issue. according to [this](https://learn.microsoft.com/en-us/dotnet/api/system.io.fileinfo.open?view=net-8.0#system-io-fileinfo-open(system-io-filemode)), the returned stream is already in read/write access mode. adding `FileAccess.Write` is redundant. can you please post your stack trace for us better understand the issue you encountered?

also did you provide a value for `PersistentDataPath`? you might not have access to the default path in a cloud environment. so if you did not provide your own value for `PersistentDataPath`, please try to provide one and make sure you have access to that path.

**Comment by Chiel75** [comment] 2024-02-08 06:56
Hi @wenxi-zeng Yes, I did add a local persistentdatapath, I see the 2 folders created and the settings file so I have access to the path.
If you follow the link you provided to the fileMode where you can lookup that "FileMode.Append can be used only in conjunction with FileAccess.Write". You can find it here: https://learn.microsoft.com/en-us/dotnet/api/system.io.filemode?view=net-8.0

**Comment by wenxi-zeng** [comment] 2024-02-08 16:48
hi @Chiel75 after investigating `FileStream`'s source code, we can confirm your concern is valid. according to this [line](https://github.com/microsoft/referencesource/blob/master/mscorlib/system/io/filestream.cs#L734), Append should be used along with a write-only access. [FileInfo.Open](https://github.com/microsoft/referencesource/blob/master/mscorlib/system/io/fileinfo.cs#L406) by default uses ReadWrite access which will lead to an invalid append mode exception. 
I'm surprised though that we were not able to reproduce the exception and it works fine in our unit tests. we will get this fixed asap and release a new version out. thanks again for bringing this issue to our attention

**Comment by MichaelGHSeg** [comment] 2024-02-08 20:04
2.3.3 is now released with a fix for this.  Cheers!

**Closed by MichaelGHSeg** 2024-02-08 20:04 UTC
