### ISSUE TITLE
Segment.Analytics.Mediator - Exception when initialising Analytics on iOS

### ISSUE THREAD

**Issue by IainS1986** [segmentio/Analytics-CSharp#97] opened 2024-03-13 10:32 UTC
**Describe the bug**
I've just seen a consistent exception on my device (we've been using Segment for some time in Xamarin Native, have ported over to .net8, been running for a while but this is a random edge case it seems as its a new crash i've not seen before).

Just basic init below...

```
var configuration = new Configuration(SegmentKey,
                flushAt: 20,
                flushInterval: 30);
_analytics = new Analytics(configuration);
```

Theres an exception thrown,

```
System.AggregateException
2024-03-13 10:28:04.755 xxx.iOS[12074:9672560] A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Object reference not set to an instance of an object.)

---- Inner Exception
System.NullReferenceException
Object reference not set to an instance of an object.
   at Segment.Analytics.Mediator.<>c__DisplayClass1_0.<<Add>b__0>d.MoveNext()
```

**Platform (please complete the following information):**
 - Library Version in use: Segment.Analytics.CSharp/2.3.1
 - Platform being tested: iOS on .net8

**Comment by IainS1986** [comment] 2024-03-13 10:36
It *appears* like everything still works fine, but the exception is being uncaught in a Task I believe inside Segement, which means I can't catch it and it fires off into our global error/exception handling for uncaught exceptions which is a pain

**Comment by wenxi-zeng** [comment] 2024-03-13 18:32
hi @IainS1986 thanks for reporting this issue. could you first try the following to help us better understand the problem:

1. update the SDK to the latest version, see if the issue still persists
2. follow this [example](https://github.com/segmentio/Analytics-CSharp/blob/main/Samples/ConsoleSample/Program.cs#L11) to log the exception. if it's an `AggregateException`, log the inner exceptions as well

**Comment by nmaricmoberg** [comment] 2024-03-18 15:19
@wenxi-zeng I can confirm having the same issue on 2.3.3

Sentry logs it as `UnobservedTaskException`.

`System.NullReferenceException` --- `async Task <>c__DisplayClass1_0.<Add>b__0(?)+(?) => { }`

Assembly: `Segment.Analytics.CSharp`
Version: `2.3.3.0`

Will update to 2.3.4 and report back.

**Comment by MichaelGHSeg** [comment] 2024-03-18 20:24
From a bit of investigation, I thought we were already checking the settings and I wouldn't expect any other references to be null at that point.  I'll keep looking.  @nmaricmoberg, could you provide more of the Segment logs?

**Comment by nmaricmoberg** [comment] 2024-03-19 08:56
@wenxi-zeng @MichaelGHSeg Hey there. Thanks for taking a look into this.
I have added the exception handler in the Analytics ctor. Also updated to version 2.3.4.0

I am using .NET Native for Android and iOS, i.e. my mobile projects are targeting net8.0-android and net8.0-ios respectively.

System.TypeLoadException
```Could not load type of field 'Segment.Analytics.Analytics+<Update>d__71:<>t__builder' (1) due to: Could not resolve type with token 01000031 from typeref (expected class 'System.Runtime.CompilerServices.AsyncVoidMethodBuilder' in assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51') assembly:netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type:System.Runtime.CompilerServices.AsyncVoidMethodBuilder member:(null)```

Also, during build, AOT compilation is not possible and this is a warning that jumps out regardless of AOT or not (occured in all previous versions as well):
```
2>resource Segment.Analytics.CSharp.xml in Segment.Analytics.CSharp, Version=2.3.4.0, Culture=neutral, PublicKeyToken=null(8,10): warning IL2008: Segment.Analytics.CSharp: Could not resolve type 'System.Linq.Expressions.Interpreter.LightLambda'.
2>resource Segment.Analytics.CSharp.xml in Segment.Analytics.CSharp, Version=2.3.4.0, Culture=neutral, PublicKeyToken=null(8,10): warning IL2008: Segment.Analytics.CSharp: Could not resolve type 'System.Linq.Expressions.Interpreter.LightLambda'.
2>resource Segment.Analytics.CSharp.xml in Segment.Analytics.CSharp, Version=2.3.4.0, Culture=neutral, PublicKeyToken=null(8,10): warning IL2008: Segment.Analytics.CSharp: Could not resolve type 'System.Linq.Expressions.Interpreter.LightLambda'.
2>resource Segment.Analytics.CSharp.xml in Segment.Analytics.CSharp, Version=2.3.4.0, Culture=neutral, PublicKeyToken=null(8,10): warning IL2008: Segment.Analytics.CSharp: Could not resolve type 'System.Linq.Expressions.Interpreter.LightLambda'.
```

**Comment by nmaricmoberg** [comment] 2024-03-19 10:50
I have managed to **_mitigate_** the System.TypeLoadException error by creating an extra project XYZ.Common that targets **netstandard2.1**. The .NET 8 target causes that issue. I only reference Segment Analytics CSharp 2.3.4 in that project and I hold a static Analytics instance there that both projects (iOS and Android) use.

I believe you need to directly add support for .NET 5-6-7-8 in the package.

The build warnings are still there, and the original issue that Sentry reported is still there:
```
System.NullReferenceException
Object reference not set to an instance of an object
async void Mediator.Add(Plugin plugin)+(?) => { }
```

**Comment by wenxi-zeng** [comment] 2024-03-19 18:36
@nmaricmoberg thanks for this detailed logs and diagnosing info. it's super. we'll take a look. in the meanwhile, please keep using the workaround you proposed. sorry for the inconvenience it may cause.

**Comment by alimakki** [comment] 2024-04-17 00:05
Getting a similar error as this, however in Unity, limited stacktrace captured from sentry.

I used the [UnitySample](https://github.com/segmentio/Analytics-CSharp/tree/main/Samples/UnitySample) patterns in our code to configure and Segment.

```
System.NullReferenceException
 
Segment.Analytics.Mediator+<>c__DisplayClass1_0+<<Add>b__0
```

Using the following version of Segment `2.3.4.0`

**Comment by dimitri-dev** [comment] 2024-04-17 10:05
@alimakki Try building the fix for #98 locally and running with that. Wish it was an actual confirmed fix and released but the maintainers are a little bit busy I guess?

**Comment by IainS1986** [comment] 2024-04-17 22:03
Just an FYI in case people weren't aware. 

I'm getting this on Android too.

**Comment by MiBu** [comment] 2024-04-18 09:17
@wenxi-zeng we are lso seeing this issue and trying the fix from https://github.com/segmentio/Analytics-CSharp/pull/98 fixes it, but we are not comfortable deploying without you taking a look and approving it.

**Comment by wenxi-zeng** [comment] 2024-04-22 23:18
hi all, the latest version `2.3.5` is released with the fix @dimitri-dev proposed. we have verified the issue is resolved on our test devices. thanks!

**Closed by wenxi-zeng** 2024-04-22 23:18 UTC

**Comment by alimakki** [comment] 2024-04-23 13:09
Thank you @wenxi-zeng @dimitri-dev
